Repository harness/canary, pull requests merged in 2025-01, with the labels that each got.

#640 feat: update commit-details page
  apps/design-system/src/pages/view-preview/commit-details-diff-view-wrapper.tsx
  apps/design-system/src/pages/view-preview/commit-details-view-wrapper.tsx
  apps/design-system/src/pages/view-preview/repo-files-view-wrapper.tsx
  apps/design-system/src/pages/view-preview/view-preview.tsx
  apps/design-system/src/subjects/views/commit-details/commit-details-store.ts
  apps/design-system/src/subjects/views/commit-details/index.tsx
  apps/design-system/src/subjects/views/repo-commits/index.tsx
  apps/design-system/src/utils/fileViewUtils.tsx
  apps/gitness/src/RouteDefinitions.ts
  apps/gitness/src/components/FileExplorer.tsx
  apps/gitness/src/pages-v2/repo/repo-commit-details-diff.tsx
  apps/gitness/src/pages-v2/repo/repo-commit-details.tsx
  apps/gitness/src/pages-v2/repo/repo-commits.tsx
  apps/gitness/src/pages-v2/repo/stores/commit-details-store.ts
  apps/gitness/src/routes.tsx
  packages/ui/locales/en/component.json
  packages/ui/locales/en/views.json
  packages/ui/locales/es/component.json
  packages/ui/locales/es/views.json
  packages/ui/locales/fr/component.json
  packages/ui/locales/fr/views.json
  packages/ui/src/components/copy-button.tsx
  packages/ui/src/views/project/project-labels/components/create-label-dialog.tsx
  packages/ui/src/views/project/project-labels/components/labels-list-view.tsx
  packages/ui/src/views/repo/components/commits-list.tsx
  packages/ui/src/views/repo/index.ts
  packages/ui/src/views/repo/pull-request/compare/components/pull-request-compare-diff-list.tsx
  packages/ui/src/views/repo/pull-request/components/pull-request-labels-list.tsx
  packages/ui/src/views/repo/pull-request/components/pull-request-reviewers-header.tsx
  packages/ui/src/views/repo/pull-request/details/components/changes/pull-request-changes-filter.tsx
  packages/ui/src/views/repo/repo-commit-details/commit-diffs-view.tsx
  packages/ui/src/views/repo/repo-commit-details/components/commit-changes.tsx
  packages/ui/src/views/repo/repo-commit-details/components/commit-diff.tsx
  packages/ui/src/views/repo/repo-commit-details/components/commit-sidebar.tsx
  packages/ui/src/views/repo/repo-commit-details/components/index.ts
  packages/ui/src/views/repo/repo-commit-details/index.ts
  packages/ui/src/views/repo/repo-commit-details/index.tsx
  packages/ui/src/views/repo/repo-commit-details/repo-commit-details-view.tsx
  packages/ui/src/views/repo/repo-commits/repo-commits-view.tsx
Labels: not-ready-for-review

#677 Fixed api route for download file and view raw file
  apps/gitness/src/components-v2/file-content-viewer.tsx
  apps/gitness/src/framework/hooks/useDownloadRawFile.ts
Labels: bug

#690 Fixed a few issues from MFE Bugbash India sheet
  packages/ui/src/shared-style-variables.css
  packages/ui/src/views/repo/components/branch-info-bar.tsx
  packages/ui/src/views/repo/components/branch-selector/branch-selector-dropdown.tsx
  packages/ui/src/views/repo/pull-request/components/pull-request-list-header.tsx
Labels: bug

#841 Fixed breadcrumb failing API issue for MFE
  apps/gitness/src/AppMFE.tsx
Labels: bug

#865 MFE Bug Fixes
  apps/gitness/src/AppMFE.tsx
  apps/gitness/src/hooks/useLoadMFEStyles.ts
  apps/gitness/src/routes.tsx
  packages/ui/package.json
  packages/ui/src/components/markdown-viewer/style.css
  packages/ui/src/views/repo/repo-list/repo-list.tsx
  packages/yaml-editor/src/utils/blame-editor-utils.ts
Labels: bug

#862 docs: added support for multi-select
  apps/portal/src/content/docs/components/multi-select.mdx
Labels: documentation

#861 Added useAPIPath hook to check for mfe condition
  apps/gitness/src/components-v2/file-content-viewer.tsx
  apps/gitness/src/framework/hooks/useDownloadRawFile.ts
  apps/gitness/src/hooks/useAPIPath.ts
Labels: enhancement
